INSERT INTO PortfolioMedia (id, title, brand, type, location, imageSrc, description, altText, displayOrder, isFeatured) VALUES
('gofy-multan-campaign', 'Gofy Brand - Multan Campaign', 'GOFY', 'BILLBOARD', 'Bosan Road, Block C, Multan', '/portfolio/gofy-multan.jpg', 'Oatmilk Cereal Bar campaign placed along Bosan Road, Multan.', 'Gofy Brand - Multan Campaign', 1, 0),
('gofy-multan-gulgasht', 'Gofy Brand - Gulgasht Campaign', 'GOFY', 'BILLBOARD', 'Gulgasht Colony, Multan', '/portfolio/gofy-multan-gulgasht.jpg', 'High-impact OOH display placement for Gofy Oatmilk Cereal Bar in Gulgasht Colony, Multan.', 'Gofy Brand - Gulgasht Campaign', 2, 0),
('gofy-kpk-peshawar', 'Gofy Brand - KPK Campaign (Peshawar)', 'GOFY', 'BILLBOARD', 'Peshawar, KPK', '/portfolio/gofy-kpk-peshawar.jpg', 'Night-time OOH display placement for Gofy Oatmilk Cereal Bar in Peshawar, KPK.', 'Gofy Brand - KPK Campaign (Peshawar)', 3, 0),
('gofy-kpk-saddar', 'Gofy Brand - Saddar Road Campaign', 'GOFY', 'OVERHEAD GANTRY', 'Peshawar Cantt, KPK', '/portfolio/gofy-kpk-saddar.jpg', 'Prime overhead billboard display for Gofy Oatmilk Cereal Bar along Saddar Road, Peshawar Cantt.', 'Gofy Brand - Saddar Road Campaign', 4, 0),
('gofy-lahore-bhati', 'Gofy Brand - Bhati Chowk Campaign', 'GOFY', 'LARGE FORMAT BILLBOARD', 'Bhati Chowk, Lahore', '/portfolio/gofy-lahore-bhati.jpg', 'Prominent rooftop OOH display placement for Gofy Oatmilk Cereal Bar at Bhati Chowk, Lahore.', 'Gofy Brand - Bhati Chowk Campaign', 5, 0),
('gofy-muridke-campaign', 'Gofy Brand - Muridke Highway Campaign', 'GOFY', 'HIGHWAY BILLBOARD', 'Muridke, Punjab', '/portfolio/gofy-muridke.jpg', 'High-visibility roadside billboard placement for Gofy Oatmilk Cereal Bar on GT Road, Muridke.', 'Gofy Brand - Muridke Highway Campaign', 6, 0),
('study-icon-peshawar', 'Study ICON - Peshawar Campaign', 'Study ICON', 'LARGE FORMAT BILLBOARD', 'University Road, Peshawar, KPK', '/portfolio/study-icon-peshawar.jpg', 'High-visibility billboard placement for Study ICON Study Abroad Consultants in Peshawar.', 'Study ICON - Peshawar Campaign', 7, 0),
('ieeep-fair-2026', 'IEEEP Fair 2026 - Industrial Mega Exhibition', 'IEEEP Fair', 'ILLUMINATED BILLBOARD', 'Expo Center, Lahore', '/portfolio/ieeep-fair-2026.jpg', 'Illuminated nighttime event billboard for IEEEP Fair Industrial Exhibition near Expo Center Lahore.', 'IEEEP Fair 2026 - Industrial Mega Exhibition', 8, 1),
('study-icon-johar-town', 'Study ICON - Johar Town Campaign', 'Study ICON', 'ILLUMINATED BILLBOARD', 'Johar Town, Lahore', '/portfolio/study-icon-johar-town.jpg', 'Night-time high-visibility billboard display for Study ICON Study Abroad Consultants in Johar Town, Lahore.', 'Study ICON - Johar Town Campaign', 9, 1);
